{
    "name": "Export Documents",
    "version": "1.0",
    "author": "Anshika",
    "license": "LGPL-3",
    "category": "Sales",
    "summary": "Export Invoice from Sale Order (Exporter Ref + Consignee)",
    "depends": ["sale", "account", "stock", "product","product_packaging_dimensions"],
    "data": [
        "security/ir.model.access.csv",
        "reports/export_invoice_template.xml",
        "reports/export_invoice_print_button.xml",
        "reports/export_invoice_report.xml",
        "reports/tax_invoice_report.xml",
        "reports/packing_list_template.xml",
        "reports/packing_list_batch_report.xml",
        "reports/packing_list_delivery_template.xml",
        "reports/packing_list_delivery_report.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_picking_batch_view.xml",
        # "views/product_template_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}